products = [
    {
        '_id': "1",
        'name': "Airpods Wireless Bluetooth Headphones",
        'image': "images/airpods.jpeg",
        'description':
            "Bluetooth technology lets you connect it with compatible devices wirelessly High-quality",
        'brand': "Apple",
        'category': "Electronics",
        'price': 89.99,
        'countInStock': 0,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        '_id': "2",
        'name': "iPhone 11",
        'image': "images/phone.jpeg",
        'description':
            "The iPhone 11 has a 6.1-inch (15 cm) IPS LCD with a resolution is 1792 - 828 pixels (1.4 megapixels) at a pixel density of 326 PPI with a maximum brightness of 625 nits and a 1400:1 contrast ratio and it is equivalent to the iPhone XR. It supports Dolby Vision, HDR10, True-Tone, and a wide color gamut.",
        'brand': "Apple",
        'category': "Electronics",
        'price': 599.99,
        'countInStock': 7,
        'rating': 4.0,
        'numReviews': 8,
    },
    {
        '_id': "3",
        'name': "Cannon EOS 80D DSLR Camera",
        'image': "images/camera.png",
        'description':
            "Scene Intelligent Auto (Stills and Movie), No Flash, Creative Auto, SCN(Portrait, Landscape, Close-up, Sports, Night Portrait",
        'brand': "Cannon",
        'category': "Electronics",
        'price': 929.99,
        'countInStock': 5,
        'rating': 3.0,
        'numReviews': 12,
    },
    {
        '_id': "4",
        'name': "Sony Playstation 5",
        'image': "images/playstation.webp",
        'description':
            "The PlayStation 5 (PS5) is a home video game console developed by Sony Interactive Entertainment",
        'brand': "Sony",
        'category': "Electronics",
        'price': 399.99,
        'countInStock': 11,
        'rating': 5,
        'numReviews': 12,
    },
    {
        '_id': "5",
        'name': "Logitech G-Series Gaming Mouse",
        'image': "images/mouse.jpg",
        'description':
            "A gaming mouse performs the same role as your regular mouse, it does so with a higher level of precision",
        'brand': "Logitech",
        'category': "Electronics",
        'price': 49.99,
        'countInStock': 7,
        'rating': 3.5,
        'numReviews': 10,
    },
    {
        '_id': "6",
        'name': "Amazon Alexa",
        'image': "images/alexa.jpeg",
        'description': "Bluetooth technology that talks to you",
        'brand': "Amazon",
        'category': "Electronics",
        'price': 29.99,
        'countInStock': 0,
        'rating': 4,
        'numReviews': 12,
    },
]
